[build]
  base = "tracker-client"
  publish = ".next"
  command = "npm install && npm run build"

[context.production.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  inputs = {}